### PR TITLE
Earthsci preprint matching.2023 nov02

### PR DESCRIPTION
**Pull request by seasidesparrow**

### CODE REVIEW

**Review by golnazads — COMMENTED** [review]
My understanding has been that earth science records can be combined with arXiv records in the same input file. The way that you have it, you have separated it, I understand because you want to be able to use different parser. And the reverse of this, matching publisher with arXiv is straightforward and the input file can contain the earth science records in the list since all can go through the same parser.

So here is what I am proposing. Pass the pub_filename to the routine, do not identify it if it is arXiv or not in the run.py. Basically keep it as it was before. This way again match_to_arXiv and match_to_pub will have the same signature and the same behavior.

So in the single_match_to_arXiv function decide which parser to use base on path. As you know the path is basically set in stone. I am using the path in reference pipeline to tell which parser to use. So we can apply the same logic here. Basically, grab the section of the path that represent the bibstem and that is in the /source directory, then check if it is arXiv and call arXiv parser, otherwise call the generic parser.

This way the same logic is applied on the both side, any path can be included in the input file, and we have encapsulate the logic in the class not outside of it.

What do you think?

**Comment by seasidesparrow** [comment]
I think it comes down to deciding whether to have the parser doing system-level logic, or whether the parser acts based upon what the controlling code tells it to do.  In this case, the pathnames are definite _only at this moment in time_, but we're in a transition period where the underlying system architecture or flow control may change.  If we use a calling option like what I've implemented to specify that logic, we're not reliant on the current architecture, and that would be my preference.

**Comment by aaccomazzi** [comment]
I'm pretty sure we had this conversation a few months back and from my perspective nothing has changed, so let me restate what I think we should do:

1. Unify the format for the input list of records to be matched -- right now for arXiv we read the source DC XML but there is no reason why we could not use the classic metadata files, which have the same format for both eprint and published records. If we do that, we have a single read function that at some point can be swapped out in the future with a read from a database. The input in all cases can simply be the full path of the metadata files.
2. Implement trivial logic that decides whether the input metadata is for an eprint or not -- right now this is a 2-line function simply checking the bibstem (extracted from the bibcode) and not the pathname, but to further future-proof this for the day when the bibcode/bibstem may not be there we would have a metadata field provide the same information from our ingest data model
3. There is no 3: if the input is an eprint call the match_to_published function, and vice-versa

If I missed/misunderstood something let's have a chat.

**Comment by golnazads** [comment]
@aaccomazzi 
I did not know that the classic format can correctly read arXiv metadata. Then we should remove the arXiv parser and use the classic reader for all input files this way there is no need to identify what kind the input metadata file is. That should solve the issue. Thank you. 
@seasidesparrow

**Comment by golnazads** [comment]
@seasidesparrow
I have time today, I can verify that classic parser can read the arXiv file and extract all the information that arXiv parser extracts. Let me know if you want me to do that.

**Comment by seasidesparrow** [comment]
I would need to make some changes to the classic side to have it output paths to the .abs files instead of to the xml files and test it, so this isn't something I would want to deploy before next Tuesday at the earliest.

**Comment by golnazads** [comment]
@seasidesparrow 
Let me check it out. I shall let you know what I found out.

**Comment by golnazads** [comment]
@seasidesparrow 
I went ahead implemented this and made a release, if you would please check it out.
https://github.com/adsabs/ADSDocMatchPipeline/releases/tag/v3.1.4
Now you can include earth science records among the arXiv records and submit them to pipeline to get matched with publication. Or included them among the pub records and submit them to get matched with arXiv records. You can also submit them separately, for example if earth science records come as eprints during the weekend, you can create eprint.input list and process them then, the same if they come in as pub records at any time, you can create pub.input and process them at once. Very flexible. Please let me know if there is any issue. thank you.
@aaccomazzi

**Comment by seasidesparrow** [comment]
Closed: superseded

**Pull request closed without merging**
